### ISSUE TITLE
[ feature ] 페이지 - city 페이지 만들기

### ISSUE THREAD

**Issue by chaeneey** [SOPT-all/35-COLLABORATION-WEB-AGODA#16]
## 📄 설명

<img width="291" alt="스크린샷 2024-11-19 오후 5 25 46" src="https://github.com/user-attachments/assets/461166c2-e8e8-4ff3-9b62-925214f5eb25">

## ✅ To-do

- [x] 페이지 컴포넌트 - 도시 헤더
- [x] 페이지 컴포넌트 - 도시 카드
- [x] 페이지 - mock 데이터 만들어서 map 돌리기
