### ISSUE TITLE
[ setting ] Tanstack Query, API 초기 세팅

### ISSUE THREAD

**Issue by m2na7** [SOPT-all/35-COLLABORATION-WEB-AGODA#33]
## 📄 설명

Tanstack Query 초기 세팅을 진행합니다.

## ✅ To-do

- [x] Devtools 설정
- [x] QueryClient, Provider 설정
- [x] axios Instance 설정
- [x] END_POINT 설정
